# @format

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    user: '501:20'
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@volodymyrshcherbyna.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
      - ./data/pgadmin-log:/var/log/pgadmin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.workstation`)'
      - 'traefik.http.routers.pgadmin.entrypoints=web'
      - 'traefik.http.services.pgadmin.loadBalancer.server.port=80'

    networks:
      - workstation

networks:
  workstation:
    name: 'workstation'
