# @format

services:
  n8n:
    image: 'docker.n8n.io/n8nio/n8n:latest'
    container_name: n8n
    restart: always
    user: 'root'
    env_file:
      - ./docker-compose.n8n.env
    networks:
      - workstation
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.n8n.rule=Host(`n8n.workstation`)'
      - 'traefik.http.routers.n8n.entrypoints=web'
      - 'traefik.http.services.n8n.loadBalancer.server.port=5678'
    volumes:
      - './data/n8n-data:/home/node/.n8n'
      - '~/.ssh:/home/developer/.ssh'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'macbook-pro.local:192.168.0.118'
      - 'n8n.workstation:192.168.0.118'

networks:
  workstation:
    name: 'workstation'
