# @format

services:
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: always
    user: '501:20'
    networks:
      - workstation
    volumes:
      - './data/redis-data:/data'

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    user: '501:20'
    depends_on:
      - redis
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.redisinsight.rule=Host(`redis-insight.workstation`)'
      - 'traefik.http.routers.redisinsight.entrypoints=web'
      - 'traefik.http.services.redisinsight.loadBalancer.server.port=5540'
    networks:
      - workstation
    volumes:
      - './data/redisinsight-data:/data'

networks:
  workstation:
    name: 'workstation'
